import * as vscode from 'vscode';
import * as path from 'path';
import { getWorkspaceRoot, buildDependencyMap } from '../utils/contextBuilder';

export class DependencyGraphPanel {
  static currentPanel?: DependencyGraphPanel;
  private readonly _panel: vscode.WebviewPanel;

  static show(context: vscode.ExtensionContext) {
    if (DependencyGraphPanel.currentPanel) {
      DependencyGraphPanel.currentPanel._panel.reveal();
      return;
    }
    const panel = vscode.window.createWebviewPanel(
      'codelensai.depGraph',
      'Dependency Graph — CodeLens AI',
      vscode.ViewColumn.Beside,
      { enableScripts: true, retainContextWhenHidden: true }
    );
    DependencyGraphPanel.currentPanel = new DependencyGraphPanel(panel);
    panel.onDidDispose(() => { DependencyGraphPanel.currentPanel = undefined; });
  }

  private constructor(panel: vscode.WebviewPanel) {
    this._panel = panel;
    this._panel.webview.html = this._loadingHtml();
    this._load();
  }

  private async _load() {
    const rootPath = getWorkspaceRoot();
    if (!rootPath) {
      this._panel.webview.html = '<body style="background:#0d0f14;color:#ccc;padding:24px;font-family:sans-serif">No workspace open.</body>';
      return;
    }

    const rawNodes = buildDependencyMap(rootPath);

    // Build edge list with duplicate guard
    const edgeSet = new Set<string>();
    const edges: Array<{ from: string; to: string }> = [];

    for (const node of rawNodes) {
      const srcId = node.relativePath.replace(/\\/g, '/');
      const dir = path.dirname(node.relativePath);

      for (const imp of node.imports) {
        const resolved = path.join(dir, imp).replace(/\\/g, '/');
        const target = rawNodes.find(n => {
          const p = n.relativePath.replace(/\\/g, '/').replace(/\.[^.]+$/, '');
          return p === resolved || p.endsWith('/' + resolved) || p === imp.replace(/\.[^.]+$/, '');
        });
        if (!target) { continue; }
        const tgtId = target.relativePath.replace(/\\/g, '/');
        if (tgtId === srcId) { continue; }
        const key = `${srcId}|||${tgtId}`;
        if (edgeSet.has(key)) { continue; }
        edgeSet.add(key);
        edges.push({ from: srcId, to: tgtId });
      }
    }

    const graphData = {
      nodes: rawNodes.map(n => ({
        id: n.relativePath.replace(/\\/g, '/'),
        label: path.basename(n.relativePath),
        ext: path.extname(n.relativePath).slice(1),
      })),
      edges,
    };

    this._panel.webview.html = this._graphHtml(JSON.stringify(graphData));
  }

  private _loadingHtml(): string {
    return `<html><body style="background:#0d0f14;color:#ccc;display:flex;align-items:center;justify-content:center;height:100vh;font-family:sans-serif;font-size:14px">
      <div style="text-align:center;opacity:.6">
        <div style="font-size:32px;margin-bottom:12px">&#x1F4C1;</div>
        <div>Scanning project files…</div>
      </div></body></html>`;
  }

  private _graphHtml(graphDataJson: string): string {
    // All JS/CSS written as plain string arrays — zero TS template-literal escaping issues

    const css = [
      '*{box-sizing:border-box;margin:0;padding:0}',
      ':root{--bg:#0d0f14;--surface:#13161e;--surface2:#1a1e29;--border:#252a38;--accent:#6c63ff;--accent2:#00d4aa;--accent3:#ff6b6b;--text:#e2e4ed;--muted:#6b7280;--mono:"JetBrains Mono",monospace}',
      'body{background:var(--bg);color:var(--text);font-family:"Segoe UI",sans-serif;height:100vh;overflow:hidden;display:flex;flex-direction:column}',
      '#toolbar{display:flex;align-items:center;gap:10px;padding:10px 16px;background:var(--surface);border-bottom:1px solid var(--border);flex-shrink:0;flex-wrap:wrap}',
      '#toolbar h2{font-size:13px;font-weight:700;color:var(--text);flex:1;letter-spacing:-.3px}',
      '#search{background:var(--surface2);border:1px solid var(--border);color:var(--text);padding:6px 12px;border-radius:6px;font-size:11px;width:200px;outline:none;font-family:var(--mono);transition:border-color .2s}',
      '#search:focus{border-color:var(--accent)}#search::placeholder{color:var(--muted)}',
      '#stats{font-family:var(--mono);font-size:11px;color:var(--muted)}',
      '.tbtn{font-family:var(--mono);font-size:10px;padding:5px 12px;background:transparent;border:1px solid var(--border);color:var(--muted);border-radius:5px;cursor:pointer;transition:all .15s;white-space:nowrap}',
      '.tbtn:hover{border-color:var(--accent2);color:var(--accent2)}.tbtn.on{border-color:var(--accent);color:var(--accent)}',
      '#canvas{flex:1;width:100%;min-height:0;display:block;cursor:grab;background:radial-gradient(ellipse at 50% 40%,#0f1420 0%,var(--bg) 100%)}',
      '#canvas:active{cursor:grabbing}',
      '#tooltip{position:fixed;background:#1a1e29;border:1px solid var(--border);border-radius:10px;padding:12px 15px;font-size:11px;font-family:var(--mono);pointer-events:none;display:none;max-width:300px;z-index:999;box-shadow:0 16px 48px rgba(0,0,0,.7)}',
      '.tt-name{font-weight:700;color:var(--text);margin-bottom:6px;font-size:12px;word-break:break-all}',
      '.tt-row{color:var(--muted);line-height:1.8}.tt-hl{color:var(--accent2)}',
      '.tt-badge{display:inline-block;background:rgba(108,99,255,.15);border:1px solid rgba(108,99,255,.3);color:#a89fff;padding:1px 7px;border-radius:10px;font-size:10px;margin:2px 3px 2px 0}',
      '#legend{display:flex;align-items:center;gap:14px;padding:7px 16px;background:var(--surface);border-top:1px solid var(--border);font-size:10px;color:var(--muted);flex-shrink:0;flex-wrap:wrap}',
      '.leg{display:flex;align-items:center;gap:5px}.dot{width:10px;height:10px;border-radius:50%;flex-shrink:0}',
      '.hint{margin-left:auto;font-size:10px;color:var(--muted);opacity:.7}',
    ].join('\n');

    const js = [
      'var DATA=' + graphDataJson + ';',
      '',
      '// ── Ext colors ────────────────────────────────────────────────',
      'var EC={ts:"#5ba3f5",tsx:"#5ba3f5",js:"#f0c030",jsx:"#f0c030",py:"#4caf50",go:"#00acd7",',
      '  rs:"#f46623",css:"#ab77f7",scss:"#ab77f7",html:"#f07070",json:"#4db6ac",md:"#60a0c0"};',
      '',
      '// ── Pre-compute degrees ────────────────────────────────────────',
      'var deg={};',
      'for(var di=0;di<DATA.edges.length;di++){',
      '  deg[DATA.edges[di].from]=(deg[DATA.edges[di].from]||0)+1;',
      '  deg[DATA.edges[di].to]=(deg[DATA.edges[di].to]||0)+1;',
      '}',
      '',
      '// ── Node objects ──────────────────────────────────────────────',
      'var nodes=DATA.nodes.map(function(n){',
      '  return {id:n.id,label:n.label,ext:n.ext,',
      '    x:0,y:0,vx:0,vy:0,fixed:false,_deg:deg[n.id]||0};',
      '});',
      'var edges=DATA.edges;',
      '',
      '// ── State ─────────────────────────────────────────────────────',
      'var selectedId=null,filterText="";',
      'var panX=0,panY=0,zoom=1;',
      'var dragNode=null,isPan=false,panStart=null;',
      'var simTick=0,ready=false;',
      '',
      '// ── Canvas / ctx ──────────────────────────────────────────────',
      'var canvas=document.getElementById("canvas");',
      'var ctx=canvas.getContext("2d");',
      'var tip=document.getElementById("tooltip");',
      'var statsEl=document.getElementById("stats");',
      '',
      '// ── Helpers ───────────────────────────────────────────────────',
      'function nodeR(n){return Math.max(5,Math.min(14,5+(n._deg||0)*0.9));}',
      'function nodeCol(n){',
      '  if(n.id===selectedId){return"#00d4aa";}',
      '  return(n._deg||0)>0?(EC[n.ext]||"#6c63ff"):"#3a3f50";',
      '}',
      '',
      '// ── Layout ────────────────────────────────────────────────────',
      '// KEY: only position nodes when canvas has real size.',
      '// Uses Fibonacci sphere layout → spread nodes evenly across the canvas.',
      'function initLayout(){',
      '  if(canvas.width<10||canvas.height<10){return false;}',
      '  ready=true;simTick=0;',
      '  var cx=canvas.width/2,cy=canvas.height/2;',
      '  // Sort hub nodes toward center',
      '  var sorted=nodes.slice().sort(function(a,b){return(b._deg||0)-(a._deg||0);});',
      '  var n=sorted.length;',
      '  var golden=Math.PI*(3-Math.sqrt(5));',
      '  for(var i=0;i<n;i++){',
      '    var nd=sorted[i];',
      '    // Hub nodes get smaller radius (stay near center)',
      '    var hubness=Math.min((nd._deg||0)/Math.max(sorted[0]._deg||1,1),1);',
      '    var maxR=Math.min(cx,cy)*0.82;',
      '    var r=maxR*(0.15+0.85*(1-hubness*0.7));',
      '    // Fibonacci angular spread for even coverage',
      '    var angle=i*golden;',
      '    nd.x=cx+Math.cos(angle)*r*(0.6+0.4*(i/Math.max(n-1,1)));',
      '    nd.y=cy+Math.sin(angle)*r*(0.6+0.4*(i/Math.max(n-1,1)));',
      '    nd.vx=0;nd.vy=0;nd.fixed=false;',
      '  }',
      '  return true;',
      '}',
      '',
      'function resize(){',
      '  var w=canvas.offsetWidth,h=canvas.offsetHeight;',
      '  if(w>0&&h>0){canvas.width=w;canvas.height=h;}',
      '  if(!ready&&canvas.width>10){initLayout();}',
      '}',
      '',
      'function resetView(){',
      '  panX=0;panY=0;zoom=1;selectedId=null;',
      '  ready=false;',
      '  // Slight delay so any pending resize finishes first',
      '  setTimeout(function(){',
      '    if(canvas.width<10){resize();}',
      '    initLayout();',
      '  },20);',
      '}',
      '',
      '// ── Force simulation ──────────────────────────────────────────',
      'function simulate(){',
      '  if(!ready||simTick>700){return;}',
      '  var W=canvas.width,H=canvas.height;',
      '  var k=Math.sqrt((W*H)/Math.max(nodes.length,1))*1.5;',
      '  for(var i=0;i<nodes.length;i++){nodes[i].vx=0;nodes[i].vy=0;}',
      '  // Repulsion',
      '  for(var i=0;i<nodes.length;i++){',
      '    for(var j=i+1;j<nodes.length;j++){',
      '      var a=nodes[i],b=nodes[j];',
      '      var dx=b.x-a.x||0.01,dy=b.y-a.y||0.01;',
      '      var d=Math.sqrt(dx*dx+dy*dy)||1;',
      '      var minD=nodeR(a)+nodeR(b)+18;',
      '      var f=d<minD?k*k/d*4.5:k*k/d*0.45;',
      '      var ux=dx/d,uy=dy/d;',
      '      a.vx-=ux*f;a.vy-=uy*f;',
      '      b.vx+=ux*f;b.vy+=uy*f;',
      '    }',
      '  }',
      '  // Attraction along edges',
      '  for(var ei=0;ei<edges.length;ei++){',
      '    var e=edges[ei],na=null,nb=null;',
      '    for(var ni=0;ni<nodes.length;ni++){',
      '      if(nodes[ni].id===e.from){na=nodes[ni];}',
      '      if(nodes[ni].id===e.to){nb=nodes[ni];}',
      '    }',
      '    if(!na||!nb){continue;}',
      '    var dx=nb.x-na.x,dy=nb.y-na.y,d=Math.sqrt(dx*dx+dy*dy)||1;',
      '    var ideal=100+nodeR(na)+nodeR(nb);',
      '    var f=(d-ideal)/d*0.1;',
      '    na.vx+=dx*f;na.vy+=dy*f;',
      '    nb.vx-=dx*f;nb.vy-=dy*f;',
      '  }',
      '  // Center gravity',
      '  var cx=W/2,cy=H/2;',
      '  for(var ni=0;ni<nodes.length;ni++){',
      '    var n=nodes[ni];',
      '    if(n.fixed){continue;}',
      '    n.vx+=(cx-n.x)*0.0018;n.vy+=(cy-n.y)*0.0018;',
      '    n.vx*=0.86;n.vy*=0.86;',
      '    n.x+=n.vx;n.y+=n.vy;',
      '    // Hard clamp — prevents nodes from flying off screen',
      '    var pad=nodeR(n)+2;',
      '    n.x=Math.max(pad,Math.min(W-pad,n.x));',
      '    n.y=Math.max(pad,Math.min(H-pad,n.y));',
      '  }',
      '  simTick++;',
      '}',
      '',
      '// ── Draw ──────────────────────────────────────────────────────',
      'function findN(id){for(var i=0;i<nodes.length;i++){if(nodes[i].id===id){return nodes[i];}}return null;}',
      '',
      'function draw(){',
      '  ctx.clearRect(0,0,canvas.width,canvas.height);',
      '  if(!ready||!nodes.length){',
      '    ctx.fillStyle="#6b7280";ctx.font="13px Segoe UI,sans-serif";',
      '    ctx.textAlign="center";',
      '    ctx.fillText(nodes.length?"Initialising layout…":"No files found",',
      '      canvas.width/2,canvas.height/2);',
      '    return;',
      '  }',
      '  ctx.save();ctx.translate(panX,panY);ctx.scale(zoom,zoom);',
      '',
      '  // Visible set',
      '  var vis=[];',
      '  for(var ni=0;ni<nodes.length;ni++){',
      '    var n=nodes[ni];',
      '    if(!filterText||n.id.toLowerCase().indexOf(filterText)!==-1){vis.push(n);}',
      '  }',
      '  var vs={};for(var vi=0;vi<vis.length;vi++){vs[vis[vi].id]=true;}',
      '',
      '  // Connected to selected',
      '  var sc={};',
      '  if(selectedId){',
      '    for(var ei=0;ei<edges.length;ei++){',
      '      if(edges[ei].from===selectedId){sc[edges[ei].to]="out";}',
      '      else if(edges[ei].to===selectedId){sc[edges[ei].from]="in";}',
      '    }',
      '  }',
      '',
      '  // ── Edges ────────────────────────────────────────────────',
      '  for(var ei=0;ei<edges.length;ei++){',
      '    var e=edges[ei];',
      '    if(!vs[e.from]||!vs[e.to]){continue;}',
      '    var na=findN(e.from),nb=findN(e.to);if(!na||!nb){continue;}',
      '    var hl=selectedId&&(e.from===selectedId||e.to===selectedId);',
      '    var dim=selectedId&&!hl;',
      '    var ang=Math.atan2(nb.y-na.y,nb.x-na.x);',
      '    var rA=nodeR(na),rB=nodeR(nb);',
      '    var sx=na.x+Math.cos(ang)*rA,sy=na.y+Math.sin(ang)*rA;',
      '    var ex=nb.x-Math.cos(ang)*(rB+5),ey=nb.y-Math.sin(ang)*(rB+5);',
      '    if(hl){',
      '      var g=ctx.createLinearGradient(sx,sy,ex,ey);',
      '      if(e.from===selectedId){g.addColorStop(0,"rgba(108,99,255,.95)");g.addColorStop(1,"rgba(0,212,170,.95)");}',
      '      else{g.addColorStop(0,"rgba(0,212,170,.65)");g.addColorStop(1,"rgba(108,99,255,.95)");}',
      '      ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(ex,ey);',
      '      ctx.strokeStyle=g;ctx.lineWidth=2.5/zoom;ctx.globalAlpha=1;ctx.stroke();',
      '      // Arrow',
      '      ctx.beginPath();ctx.moveTo(ex,ey);',
      '      ctx.lineTo(ex-Math.cos(ang-.38)*9/zoom,ey-Math.sin(ang-.38)*9/zoom);',
      '      ctx.lineTo(ex-Math.cos(ang+.38)*9/zoom,ey-Math.sin(ang+.38)*9/zoom);',
      '      ctx.closePath();ctx.fillStyle=e.from===selectedId?"#00d4aa":"#6c63ff";ctx.fill();',
      '    } else {',
      '      ctx.beginPath();ctx.moveTo(sx,sy);ctx.lineTo(ex,ey);',
      '      ctx.strokeStyle=dim?"rgba(37,42,56,.22)":"rgba(255,255,255,.09)";',
      '      ctx.lineWidth=.9/zoom;ctx.globalAlpha=1;ctx.stroke();',
      '    }',
      '  }',
      '',
      '  // ── Nodes ────────────────────────────────────────────────',
      '  for(var vi=0;vi<vis.length;vi++){',
      '    var nv=vis[vi];',
      '    var sel=nv.id===selectedId;',
      '    var dimN=selectedId&&!sel&&!sc[nv.id];',
      '    var r=nodeR(nv);',
      '    var col=nodeCol(nv);',
      '    ctx.globalAlpha=dimN?.15:1;',
      '',
      '    // Outer glow for selected / hub nodes',
      '    if(sel){',
      '      ctx.beginPath();ctx.arc(nv.x,nv.y,r+10,0,Math.PI*2);',
      '      ctx.fillStyle="rgba(0,212,170,.08)";ctx.fill();',
      '      ctx.beginPath();ctx.arc(nv.x,nv.y,r+5,0,Math.PI*2);',
      '      ctx.fillStyle="rgba(0,212,170,.18)";ctx.fill();',
      '    } else if((nv._deg||0)>4){',
      '      ctx.beginPath();ctx.arc(nv.x,nv.y,r+6,0,Math.PI*2);',
      '      ctx.fillStyle=(EC[nv.ext]||"#6c63ff")+"22";ctx.fill();',
      '    }',
      '',
      '    // 3D sphere — radial gradient',
      '    var grad=ctx.createRadialGradient(',
      '      nv.x-r*.3,nv.y-r*.3,r*.06,',
      '      nv.x,nv.y,r*1.1',
      '    );',
      '    if(sel){',
      '      grad.addColorStop(0,"rgba(200,255,245,.97)");',
      '      grad.addColorStop(.4,"rgba(0,212,170,.92)");',
      '      grad.addColorStop(1,"rgba(0,80,60,.55)");',
      '    } else {',
      '      var rc=parseInt(col.slice(1,3),16)||100;',
      '      var gc=parseInt(col.slice(3,5),16)||100;',
      '      var bc=parseInt(col.slice(5,7),16)||100;',
      '      grad.addColorStop(0,"rgba("+(rc+90)+","+(gc+90)+","+(bc+90)+",.97)");',
      '      grad.addColorStop(.4,"rgba("+rc+","+gc+","+bc+",.88)");',
      '      grad.addColorStop(1,"rgba("+(rc>>1)+","+(gc>>1)+","+(bc>>1)+",.5)");',
      '    }',
      '    ctx.beginPath();ctx.arc(nv.x,nv.y,r,0,Math.PI*2);ctx.fillStyle=grad;ctx.fill();',
      '',
      '    // Specular highlight',
      '    var sg=ctx.createRadialGradient(nv.x-r*.35,nv.y-r*.35,0,nv.x,nv.y,r);',
      '    sg.addColorStop(0,"rgba(255,255,255,.5)");',
      '    sg.addColorStop(.35,"rgba(255,255,255,.12)");',
      '    sg.addColorStop(1,"rgba(255,255,255,0)");',
      '    ctx.beginPath();ctx.arc(nv.x,nv.y,r,0,Math.PI*2);ctx.fillStyle=sg;ctx.fill();',
      '',
      '    // Drop shadow ellipse',
      '    ctx.beginPath();',
      '    ctx.ellipse(nv.x+r*.1,nv.y+r+2,r*.65,r*.18,0,0,Math.PI*2);',
      '    ctx.fillStyle="rgba(0,0,0,.22)";ctx.fill();',
      '',
      '    // Label',
      '    if(zoom>.4||sel||sc[nv.id]){',
      '      var fs=Math.max(8,Math.min(11,10/zoom));',
      '      ctx.font=(sel?"700 ":((nv._deg||0)>3?"600 ":""))+fs+"px JetBrains Mono,monospace";',
      '      ctx.textAlign="center";',
      '      // Shadow stroke',
      '      ctx.fillStyle="rgba(13,15,20,.85)";',
      '      ctx.fillText(nv.label,nv.x+.5,nv.y+r+fs+2.5);',
      '      // Label',
      '      ctx.fillStyle=sel?"#00d4aa":(sc[nv.id]?"#e2e4ed":((nv._deg||0)>3?col:"#9ca3af"));',
      '      ctx.fillText(nv.label,nv.x,nv.y+r+fs+2);',
      '    }',
      '    ctx.globalAlpha=1;',
      '  }',
      '  ctx.restore();',
      '',
      '  // Stats',
      '  var ec=0;for(var ei=0;ei<edges.length;ei++){if(vs[edges[ei].from]&&vs[edges[ei].to]){ec++;}}',
      '  statsEl.textContent=vis.length+" files \\u00b7 "+ec+" imports";',
      '}',
      '',
      '// ── Hit test ──────────────────────────────────────────────────',
      'function nodeAt(mx,my){',
      '  var wx=(mx-panX)/zoom,wy=(my-panY)/zoom;',
      '  for(var i=nodes.length-1;i>=0;i--){',
      '    var n=nodes[i],r=nodeR(n)+5;',
      '    if((n.x-wx)*(n.x-wx)+(n.y-wy)*(n.y-wy)<r*r){return n;}',
      '  }',
      '  return null;',
      '}',
      '',
      '// ── Events ────────────────────────────────────────────────────',
      'canvas.addEventListener("mousedown",function(e){',
      '  var n=nodeAt(e.offsetX,e.offsetY);',
      '  if(n){dragNode=n;n.fixed=true;selectedId=n.id;}',
      '  else{selectedId=null;isPan=true;panStart={x:e.offsetX-panX,y:e.offsetY-panY};}',
      '});',
      '',
      'canvas.addEventListener("mousemove",function(e){',
      '  if(dragNode){dragNode.x=(e.offsetX-panX)/zoom;dragNode.y=(e.offsetY-panY)/zoom;}',
      '  else if(isPan){panX=e.offsetX-panStart.x;panY=e.offsetY-panStart.y;}',
      '  var n=nodeAt(e.offsetX,e.offsetY);',
      '  if(n){',
      '    var deps=[],used=[];',
      '    for(var i=0;i<edges.length;i++){',
      '      if(edges[i].from===n.id){deps.push(edges[i].to.split("/").pop());}',
      '      if(edges[i].to===n.id){used.push(edges[i].from.split("/").pop());}',
      '    }',
      '    tip.style.display="block";',
      '    tip.style.left=(e.clientX+16)+"px";tip.style.top=(e.clientY-12)+"px";',
      '    var col=EC[n.ext]||"#6c63ff";',
      '    var dB=deps.slice(0,7).map(function(d){return"<span class=\'tt-badge\'>"+d+"</span>";}).join("");',
      '    var uB=used.slice(0,7).map(function(d){return"<span class=\'tt-badge\'>"+d+"</span>";}).join("");',
      '    tip.innerHTML="<div class=\'tt-name\' style=\'color:"+col+"\'>"+n.id+"</div>"',
      '      +"<div class=\'tt-row\'><span style=\'color:var(--muted)\'>Type: </span><span class=\'tt-hl\'>"+(n.ext||"?").toUpperCase()+"</span></div>"',
      '      +"<div class=\'tt-row\'><span style=\'color:var(--muted)\'>Connections: </span><span class=\'tt-hl\'>"+(n._deg||0)+"</span></div>"',
      '      +(deps.length?"<div style=\'margin-top:7px;color:var(--muted);font-size:10px;letter-spacing:.8px\'>IMPORTS</div><div>"+dB+(deps.length>7?"<span style=\'color:var(--muted)\'>+more</span>":"")+"</div>":"")',
      '      +(used.length?"<div style=\'margin-top:7px;color:var(--muted);font-size:10px;letter-spacing:.8px\'>USED BY</div><div>"+uB+(used.length>7?"<span style=\'color:var(--muted)\'>+more</span>":"")+"</div>":"");',
      '    canvas.style.cursor="pointer";',
      '  } else{tip.style.display="none";canvas.style.cursor=isPan?"grabbing":"grab";}',
      '});',
      '',
      'canvas.addEventListener("mouseup",function(){',
      '  if(dragNode){dragNode.fixed=false;dragNode=null;}isPan=false;',
      '});',
      '',
      'canvas.addEventListener("dblclick",function(e){',
      '  var n=nodeAt(e.offsetX,e.offsetY);if(n){n.fixed=!n.fixed;}',
      '});',
      '',
      'canvas.addEventListener("wheel",function(e){',
      '  e.preventDefault();',
      '  var f=e.deltaY>0?.88:1.12;',
      '  panX=e.offsetX-(e.offsetX-panX)*f;',
      '  panY=e.offsetY-(e.offsetY-panY)*f;',
      '  zoom=Math.max(.08,Math.min(zoom*f,8));',
      '},{passive:false});',
      '',
      'document.getElementById("search-input").addEventListener("input",function(){',
      '  filterText=this.value.toLowerCase();',
      '});',
      '',
      'document.getElementById("reset-btn").addEventListener("click",function(){',
      '  resetView();',
      '});',
      '',
      '// ── ResizeObserver: triggers initLayout when canvas becomes visible ──',
      'new ResizeObserver(function(){resize();}).observe(canvas);',
      'resize();// initial call',
      '',
      '// ── Main loop ─────────────────────────────────────────────────',
      'function loop(){simulate();draw();requestAnimationFrame(loop);}',
      'loop();',
    ].join('\n');

    const html = [
      '<!DOCTYPE html><html><head>',
      '<meta charset="UTF-8">',
      '<style>' + css + '</style>',
      '</head><body>',
      '<div id="toolbar">',
      '  <h2>&#x1F4C1; Dependency Graph <span style="font-size:10px;font-weight:400;color:var(--muted)">(3D)</span></h2>',
      '  <input id="search-input" placeholder="&#x1F50D; filter files…">',
      '  <span id="stats"></span>',
      '  <button class="tbtn" id="reset-btn">&#x1F504; Reset</button>',
      '</div>',
      '<canvas id="canvas"></canvas>',
      '<div id="tooltip"></div>',
      '<div id="legend">',
      '  <div class="leg"><div class="dot" style="background:#5ba3f5"></div>.ts/.tsx</div>',
      '  <div class="leg"><div class="dot" style="background:#f0c030"></div>.js/.jsx</div>',
      '  <div class="leg"><div class="dot" style="background:#4caf50"></div>.py</div>',
      '  <div class="leg"><div class="dot" style="background:#ab77f7"></div>.css/.scss</div>',
      '  <div class="leg"><div class="dot" style="background:#f07070"></div>.html</div>',
      '  <div class="leg"><div class="dot" style="background:#4db6ac"></div>.json</div>',
      '  <div class="leg"><div class="dot" style="background:#3a3f50"></div>no imports</div>',
      '  <span class="hint">Scroll=zoom &#183; Drag=move &#183; Click=select &#183; Dblclick=pin</span>',
      '</div>',
      '<script>' + js + '<\/script>',
      '</body></html>',
    ].join('\n');

    return html;
  }
}
