import * as vscode from 'vscode';
import * as path from 'path';
import { getWorkspaceRoot, buildDependencyMap } from '../utils/contextBuilder';

export class DependencyGraphPanel {
  static currentPanel?: DependencyGraphPanel;
  private readonly _panel: vscode.WebviewPanel;

  static show(context: vscode.ExtensionContext) {
    if (DependencyGraphPanel.currentPanel) {
      DependencyGraphPanel.currentPanel._panel.reveal();
      return;
    }
    const panel = vscode.window.createWebviewPanel(
      'codelensai.depGraph', 'Dependency Graph — CodeLens AI',
      vscode.ViewColumn.Beside,
      { enableScripts: true, retainContextWhenHidden: true }
    );
    DependencyGraphPanel.currentPanel = new DependencyGraphPanel(panel);
    panel.onDidDispose(() => { DependencyGraphPanel.currentPanel = undefined; });
  }

  private constructor(panel: vscode.WebviewPanel) {
    this._panel = panel;
    this._panel.webview.html = this._loadingHtml();
    this._load();
  }

  private async _load() {
    const rootPath = getWorkspaceRoot();
    if (!rootPath) {
      this._panel.webview.html = '<body style="background:#0d0f14;color:#ccc;padding:24px;font-family:sans-serif">No workspace open.</body>';
      return;
    }
    const rawNodes = buildDependencyMap(rootPath);
    const edgeSet = new Set<string>();
    const edges: Array<{ from: string; to: string }> = [];
    for (const node of rawNodes) {
      const srcId = node.relativePath.replace(/\\/g, '/');
      const dir = path.dirname(node.relativePath);
      for (const imp of node.imports) {
        const resolved = path.join(dir, imp).replace(/\\/g, '/');
        const target = rawNodes.find(n => {
          const p = n.relativePath.replace(/\\/g, '/').replace(/\.[^.]+$/, '');
          return p === resolved || p.endsWith('/' + resolved) || p === imp.replace(/\.[^.]+$/, '');
        });
        if (!target) { continue; }
        const tgtId = target.relativePath.replace(/\\/g, '/');
        if (tgtId === srcId) { continue; }
        const key = `${srcId}|||${tgtId}`;
        if (edgeSet.has(key)) { continue; }
        edgeSet.add(key);
        edges.push({ from: srcId, to: tgtId });
      }
    }
    const graphData = {
      nodes: rawNodes.map(n => ({
        id: n.relativePath.replace(/\\/g, '/'),
        label: path.basename(n.relativePath),
        ext: path.extname(n.relativePath).slice(1),
        folder: path.dirname(n.relativePath).replace(/\\/g, '/'),
      })),
      edges,
    };
    this._panel.webview.html = this._graphHtml(JSON.stringify(graphData));
  }

  private _loadingHtml(): string {
    return `<html><body style="background:#0d0f14;color:#ccc;display:flex;align-items:center;justify-content:center;height:100vh;font-family:sans-serif;font-size:14px">
      <div style="text-align:center;opacity:.6"><div style="font-size:40px;margin-bottom:14px">&#x1F4C1;</div><div>Scanning files&#8230;</div></div>
    </body></html>`;
  }

  private _graphHtml(graphDataJson: string): string {
    const css = [
      '@import url(\'https://fonts.googleapis.com/css2?family=JetBrains+Mono:wght@400;500&family=Syne:wght@700;800&display=swap\');',
      '*{box-sizing:border-box;margin:0;padding:0}',
      ':root{--bg:#0d0f14;--surface:#13161e;--surface2:#1a1e29;--border:#252a38;--accent:#6c63ff;--accent2:#00d4aa;--accent3:#ff6b6b;--text:#e2e4ed;--muted:#6b7280;--mono:\'JetBrains Mono\',monospace;--sans:\'Syne\',sans-serif}',
      'html,body{height:100%;background:var(--bg);color:var(--text);font-family:var(--sans);overflow:hidden}',
      '#app{display:grid;grid-template-rows:auto 1fr auto;height:100vh;overflow:hidden}',
      '#toolbar{display:flex;align-items:center;gap:8px;padding:8px 14px;background:var(--surface);border-bottom:1px solid var(--border);flex-shrink:0;flex-wrap:wrap}',
      '#toolbar-title{font-size:13px;font-weight:800;color:var(--text);letter-spacing:-.3px;margin-right:4px}',
      '.tb-sep{width:1px;height:20px;background:var(--border);flex-shrink:0}',
      '.tb-btn{font-family:var(--mono);font-size:10px;padding:5px 11px;background:transparent;border:1px solid var(--border);color:var(--muted);border-radius:6px;cursor:pointer;transition:all .15s;white-space:nowrap;display:inline-flex;align-items:center;gap:5px}',
      '.tb-btn:hover{border-color:var(--accent2);color:var(--accent2);background:rgba(0,212,170,.05)}',
      '.tb-btn.active{border-color:var(--accent);color:var(--accent);background:rgba(108,99,255,.08)}',
      '.zoom-group{display:flex;align-items:center;gap:0}',
      '.zoom-group .tb-btn{border-radius:0;border-right-width:0}',
      '.zoom-group .tb-btn:first-child{border-radius:6px 0 0 6px}',
      '.zoom-group .tb-btn:last-child{border-radius:0 6px 6px 0;border-right-width:1px}',
      '#zoom-val{font-family:var(--mono);font-size:10px;color:var(--muted);min-width:40px;text-align:center;padding:5px 8px;border-top:1px solid var(--border);border-bottom:1px solid var(--border);background:var(--surface2)}',
      '#search-wrap{position:relative;display:inline-flex;align-items:center}',
      '#graph-search{background:var(--surface2);border:1px solid var(--border);color:var(--text);padding:5px 28px 5px 10px;border-radius:6px;font-size:11px;width:180px;outline:none;font-family:var(--mono);transition:border-color .2s}',
      '#graph-search:focus{border-color:var(--accent)}#graph-search::placeholder{color:var(--muted)}',
      '#search-clear{position:absolute;right:7px;cursor:pointer;color:var(--muted);font-size:13px;display:none;line-height:1;user-select:none}',
      '#search-clear:hover{color:var(--accent3)}',
      '#graph-stats{font-family:var(--mono);font-size:10px;color:var(--muted);white-space:nowrap}',
      '.spacer{flex:1}',
      '#canvas-wrap{position:relative;overflow:hidden;background:radial-gradient(ellipse at 50% 40%,#0f1420 0%,var(--bg) 100%)}',
      '#graph-canvas{display:block;width:100%;height:100%;cursor:grab}',
      '#graph-canvas:active{cursor:grabbing}',
      '#tooltip{position:fixed;background:#1a1e29;border:1px solid var(--border);border-radius:10px;padding:12px 15px;font-size:11px;font-family:var(--mono);pointer-events:none;display:none;max-width:300px;z-index:999;box-shadow:0 16px 48px rgba(0,0,0,.7)}',
      '.tt-name{font-weight:700;color:var(--text);margin-bottom:7px;font-size:12px;word-break:break-all}',
      '.tt-row{color:var(--muted);line-height:1.9}.tt-hl{color:var(--accent2)}',
      '.tt-badge{display:inline-block;background:rgba(108,99,255,.15);border:1px solid rgba(108,99,255,.3);color:#a89fff;padding:1px 7px;border-radius:10px;font-size:10px;margin:2px 3px 2px 0}',
      '#info-panel{position:absolute;top:10px;right:10px;width:240px;background:#1a1e29;border:1px solid var(--border);border-radius:12px;padding:16px;font-size:11px;font-family:var(--mono);z-index:10;box-shadow:0 16px 48px rgba(0,0,0,.6);display:none;max-height:calc(100% - 20px);overflow-y:auto}',
      '#info-panel .ip-close{position:absolute;top:10px;right:10px;cursor:pointer;color:var(--muted);font-size:14px;line-height:1}',
      '#info-panel .ip-close:hover{color:var(--accent3)}',
      '#info-panel .ip-title{font-size:12px;font-weight:700;color:var(--text);margin-bottom:12px;padding-right:20px;word-break:break-all;line-height:1.5}',
      '#info-panel .ip-section{margin-top:10px}',
      '#info-panel .ip-label{font-size:9px;letter-spacing:1.2px;text-transform:uppercase;color:var(--muted);margin-bottom:5px}',
      '#info-panel .ip-badge{display:inline-block;background:rgba(0,212,170,.1);border:1px solid rgba(0,212,170,.25);color:var(--accent2);padding:2px 8px;border-radius:8px;font-size:10px;margin:2px 3px 2px 0;cursor:pointer;transition:all .15s}',
      '#info-panel .ip-badge:hover{background:rgba(0,212,170,.2)}',
      '#info-panel .ip-stat{display:flex;justify-content:space-between;padding:4px 0;border-bottom:1px solid rgba(255,255,255,.04)}',
      '#info-panel .ip-stat-label{color:var(--muted)}.ip-stat-val{color:var(--text);font-weight:600}',
      '#legend{display:flex;align-items:center;gap:14px;padding:6px 14px;background:var(--surface);border-top:1px solid var(--border);font-size:10px;color:var(--muted);flex-shrink:0;flex-wrap:wrap}',
      '.leg{display:flex;align-items:center;gap:5px}.dot{width:9px;height:9px;border-radius:50%;flex-shrink:0}',
      '.hint{margin-left:auto;font-size:10px;color:var(--muted);opacity:.6;font-family:var(--mono)}',
      '#fs-overlay{display:none;position:fixed;inset:0;background:#0d0f14;z-index:9999;flex-direction:column}',
      '#fs-toolbar{display:flex;align-items:center;gap:8px;padding:8px 14px;background:var(--surface);border-bottom:1px solid var(--border);flex-shrink:0;flex-wrap:wrap}',
      '#fs-canvas-wrap{flex:1;position:relative;overflow:hidden;background:radial-gradient(ellipse at 50% 40%,#0f1420 0%,var(--bg) 100%)}',
      '#fs-canvas{position:absolute;top:0;left:0;cursor:grab}',
      '#fs-canvas:active{cursor:grabbing}',
      '#fs-tooltip{position:fixed;background:#1a1e29;border:1px solid var(--border);border-radius:10px;padding:12px 15px;font-size:11px;font-family:var(--mono);pointer-events:none;display:none;max-width:300px;z-index:10000;box-shadow:0 16px 48px rgba(0,0,0,.7)}',
      '.cluster-badge{display:inline-block;padding:2px 8px;border-radius:20px;font-size:9px;font-weight:700;letter-spacing:.5px;cursor:pointer;transition:all .15s;margin-right:5px;margin-bottom:5px}',
      '.cluster-badge:hover{opacity:.8;transform:scale(1.05)}',
      '#kbd-hints{display:none;position:absolute;top:50%;left:50%;transform:translate(-50%,-50%);background:rgba(19,22,30,.97);border:1px solid var(--border);border-radius:14px;padding:24px 28px;z-index:20;min-width:320px;box-shadow:0 24px 80px rgba(0,0,0,.7)}',
      '#kbd-hints h3{font-size:14px;font-weight:800;color:var(--text);margin-bottom:16px}',
      '#kbd-hints .kh-close{position:absolute;top:12px;right:14px;cursor:pointer;color:var(--muted);font-size:16px}',
      '#kbd-hints .kh-close:hover{color:var(--accent3)}',
      '.krow{display:flex;align-items:center;gap:10px;margin-bottom:10px;font-size:12px;color:var(--muted)}',
      '.krow:last-child{margin-bottom:0}',
      'kbd{font-family:var(--mono);font-size:10px;background:var(--surface2);border:1px solid var(--border);padding:2px 8px;border-radius:4px;color:var(--text);white-space:nowrap}',
      '::-webkit-scrollbar{width:5px;height:5px}::-webkit-scrollbar-track{background:transparent}',
      '::-webkit-scrollbar-thumb{background:var(--border);border-radius:3px}',
    ].join('\n');

    const js = [
      'var DATA=' + graphDataJson + ';',
      'var EC={ts:"#5ba3f5",tsx:"#5ba3f5",js:"#f0c030",jsx:"#f0c030",py:"#4caf50",go:"#00acd7",rs:"#f46623",css:"#ab77f7",scss:"#ab77f7",less:"#ab77f7",html:"#f07070",json:"#4db6ac",md:"#60a0c0",vue:"#41b883",svelte:"#ff3e00",rb:"#cc342d",php:"#777bb4",java:"#b07219",cs:"#239120",cpp:"#f34b7d",c:"#555555"};',
      'var FOLDER_COLORS=["#6c63ff","#00d4aa","#ff6b6b","#f0c030","#4caf50","#00acd7","#f46623","#ab77f7","#60a0c0","#4db6ac","#5ba3f5","#ff9500"];',
      'var panX=0,panY=0,zoom=1;',
      'var dragN=null,isPan=false,panStart=null;',
      'var selId=null,hovId=null;',
      'var filterText="",filterActive=false;',
      'var clusterMode=false,clusterFocus=null;',
      'var simTick=0,ready=false;',
      'var showMinimap=true;',
      'var fsActive=false;',
      'var fsPanX=0,fsPanY=0,fsZoom=1;',
      'var fsDragN=null,fsIsPan=false,fsPanStart=null;',
      'var canvas=document.getElementById("graph-canvas");',
      'var ctx=canvas.getContext("2d");',
      'var tip=document.getElementById("tooltip");',
      'var statsEl=document.getElementById("graph-stats");',
      'var mmCanvas=document.getElementById("mm-canvas");',
      'var mmCtx=mmCanvas.getContext("2d");',
      'var mmViewport=document.getElementById("minimap-viewport");',
      'var fsCanvas=document.getElementById("fs-canvas");',
      'var fsCtx=fsCanvas.getContext("2d");',
      'var fsTip=document.getElementById("fs-tooltip");',
      'var degree={};',
      'for(var di=0;di<DATA.edges.length;di++){degree[DATA.edges[di].from]=(degree[DATA.edges[di].from]||0)+1;degree[DATA.edges[di].to]=(degree[DATA.edges[di].to]||0)+1;}',
      'var folderMap={};var folderIdx=0;',
      'for(var ni=0;ni<DATA.nodes.length;ni++){var f=DATA.nodes[ni].folder;if(!(f in folderMap)){folderMap[f]=folderIdx%FOLDER_COLORS.length;folderIdx++;}}',
      'var nodes=DATA.nodes.map(function(n){return{id:n.id,label:n.label,ext:n.ext,folder:n.folder,x:0,y:0,vx:0,vy:0,fixed:false,_deg:degree[n.id]||0,_fi:folderMap[n.folder]||0};});',
      'var edges=DATA.edges;',
      'function nR(n){return Math.max(5,Math.min(14,5+(n._deg||0)*.9));}',
      'function nColBase(n){return EC[n.ext]||"#6c63ff";}',
      'function nCol(n,mode){if(n.id===selId){return"#00d4aa";}if(mode==="cluster"){return FOLDER_COLORS[n._fi]||"#6c63ff";}return(n._deg||0)>0?nColBase(n):"#3a3f50";}',
      '',
      'function initLayout(W,H){',
      '  if(W<10||H<10){return false;}',
      '  ready=true;simTick=0;',
      '  var cx=W/2,cy=H/2;',
      '  var sorted=nodes.slice().sort(function(a,b){return(b._deg||0)-(a._deg||0);});',
      '  var golden=Math.PI*(3-Math.sqrt(5));',
      '  for(var i=0;i<sorted.length;i++){',
      '    var nd=sorted[i];',
      '    var hub=Math.min((nd._deg||0)/Math.max(sorted[0]._deg||1,1),1);',
      '    var maxR=Math.min(cx,cy)*.82;',
      '    var r=maxR*(.15+.85*(1-hub*.65));',
      '    nd.x=cx+Math.cos(i*golden)*r;nd.y=cy+Math.sin(i*golden)*r;',
      '    nd.vx=0;nd.vy=0;nd.fixed=false;',
      '  }',
      '  return true;',
      '}',
      '',
      'function doResize(){',
      '  var wrap=document.getElementById("canvas-wrap");',
      '  var W=wrap.clientWidth,H=wrap.clientHeight;',
      '  if(W>10&&H>10){canvas.width=W;canvas.height=H;}',
      '  if(!ready&&canvas.width>10){initLayout(canvas.width,canvas.height);}',
      '}',
      '',
      'function resetView(){',
      '  panX=0;panY=0;zoom=1;selId=null;ready=false;simTick=0;',
      '  for(var i=0;i<nodes.length;i++){nodes[i].x=0;nodes[i].y=0;nodes[i].vx=0;nodes[i].vy=0;nodes[i].fixed=false;}',
      '  setTimeout(function(){doResize();if(!ready){initLayout(canvas.width,canvas.height);}updateZoomUI();},30);',
      '}',
      '',
      // ── FIX: k capped at 120, velocity capped at 8 px/tick ──────────────
      'function simulate(W,H){',
      '  if(!ready||simTick>800){return;}',
      '  // FIX: cap k so large/fullscreen canvases do not explode nodes to edges',
      '  var rawK=Math.sqrt((W*H)/Math.max(nodes.length,1))*1.2;',
      '  var k=Math.min(rawK,120);',
      '  var i,j,n;',
      '  for(i=0;i<nodes.length;i++){nodes[i].vx=0;nodes[i].vy=0;}',
      '  for(i=0;i<nodes.length;i++){',
      '    for(j=i+1;j<nodes.length;j++){',
      '      var a=nodes[i],b=nodes[j];',
      '      var dx=b.x-a.x,dy=b.y-a.y;',
      '      if(Math.abs(dx)<.5&&Math.abs(dy)<.5){dx=.5-Math.random();dy=.5-Math.random();}',
      '      var d=Math.sqrt(dx*dx+dy*dy);',
      '      var minD=nR(a)+nR(b)+22;',
      '      var rep=Math.min(k*k/(d||1),k*3);if(d<minD){rep=Math.min(k*k/minD*4,k*5);}',
      '      var ux=dx/(d||1),uy=dy/(d||1);',
      '      a.vx-=ux*rep;a.vy-=uy*rep;b.vx+=ux*rep;b.vy+=uy*rep;',
      '    }',
      '  }',
      '  for(var ei=0;ei<edges.length;ei++){',
      '    var e=edges[ei],na=null,nb=null;',
      '    for(i=0;i<nodes.length;i++){if(nodes[i].id===e.from){na=nodes[i];}if(nodes[i].id===e.to){nb=nodes[i];}}',
      '    if(!na||!nb){continue;}',
      '    var exd=nb.x-na.x,eyd=nb.y-na.y,ed=Math.sqrt(exd*exd+eyd*eyd)||1;',
      '    var ideal=90+nR(na)+nR(nb);var ef=(ed-ideal)/ed*.1;',
      '    na.vx+=exd*ef;na.vy+=eyd*ef;nb.vx-=exd*ef;nb.vy-=eyd*ef;',
      '  }',
      '  var cx=W/2,cy=H/2;',
      '  for(i=0;i<nodes.length;i++){',
      '    n=nodes[i];if(n.fixed){continue;}',
      '    n.vx+=(cx-n.x)*.0025;n.vy+=(cy-n.y)*.0025;',
      '    n.vx*=.85;n.vy*=.85;',
      '    // FIX: hard velocity cap prevents explosion on large canvases',
      '    var spd=Math.sqrt(n.vx*n.vx+n.vy*n.vy);',
      '    if(spd>8){n.vx=n.vx/spd*8;n.vy=n.vy/spd*8;}',
      '    n.x+=n.vx;n.y+=n.vy;',
      '    var pad=nR(n)+3;n.x=Math.max(pad,Math.min(W-pad,n.x));n.y=Math.max(pad,Math.min(H-pad,n.y));',
      '  }',
      '  simTick++;',
      '}',
      '',
      'function findN(id){for(var i=0;i<nodes.length;i++){if(nodes[i].id===id){return nodes[i];}}return null;}',
      '',
      'function drawGraph(c,pX,pY,z,filter,sel,hov,cMode,cFocus){',
      '  c.clearRect(0,0,c.canvas.width,c.canvas.height);',
      '  if(!ready||!nodes.length){c.fillStyle="#6b7280";c.font="13px Syne,sans-serif";c.textAlign="center";c.fillText(nodes.length?"Initialising\u2026":"No files found",c.canvas.width/2,c.canvas.height/2);return;}',
      '  c.save();c.translate(pX,pY);c.scale(z,z);',
      '  var vis=[];',
      '  for(var ni=0;ni<nodes.length;ni++){var n=nodes[ni];var fM=!filter||n.id.toLowerCase().indexOf(filter)!==-1||n.label.toLowerCase().indexOf(filter)!==-1;var cM=!cMode||!cFocus||n.folder===cFocus;if(fM&&cM){vis.push(n);}}',
      '  var vs={};for(var vi=0;vi<vis.length;vi++){vs[vis[vi].id]=true;}',
      '  var sc={},hc={};',
      '  if(sel){for(var ei=0;ei<edges.length;ei++){var se=edges[ei];if(se.from===sel){sc[se.to]="out";}else if(se.to===sel){sc[se.from]="in";}}}',
      '  if(hov&&hov!==sel){for(var ei=0;ei<edges.length;ei++){var he=edges[ei];if(he.from===hov){hc[he.to]="out";}else if(he.to===hov){hc[he.from]="in";}}}',
      '  for(var ei=0;ei<edges.length;ei++){',
      '    var e=edges[ei];if(!vs[e.from]||!vs[e.to]){continue;}',
      '    var na=findN(e.from),nb=findN(e.to);if(!na||!nb){continue;}',
      '    var hl=sel&&(e.from===sel||e.to===sel);var ho=hov&&!hl&&(e.from===hov||e.to===hov);var dim=sel&&!hl;',
      '    var ang=Math.atan2(nb.y-na.y,nb.x-na.x);var rA=nR(na),rB=nR(nb);',
      '    var sx=na.x+Math.cos(ang)*rA,sy=na.y+Math.sin(ang)*rA;',
      '    var ex=nb.x-Math.cos(ang)*(rB+5),ey=nb.y-Math.sin(ang)*(rB+5);',
      '    if(hl||ho){',
      '      var g=c.createLinearGradient(sx,sy,ex,ey);var isOut=(e.from===sel||e.from===hov);',
      '      if(isOut){g.addColorStop(0,"rgba(108,99,255,.95)");g.addColorStop(1,"rgba(0,212,170,.95)");}else{g.addColorStop(0,"rgba(0,212,170,.65)");g.addColorStop(1,"rgba(108,99,255,.95)");}',
      '      c.beginPath();c.moveTo(sx,sy);c.lineTo(ex,ey);c.strokeStyle=g;c.lineWidth=(hl?2.5:1.5)/z;c.globalAlpha=hl?1:.6;c.stroke();',
      '      c.beginPath();c.moveTo(ex,ey);c.lineTo(ex-Math.cos(ang-.38)*9/z,ey-Math.sin(ang-.38)*9/z);c.lineTo(ex-Math.cos(ang+.38)*9/z,ey-Math.sin(ang+.38)*9/z);',
      '      c.closePath();c.fillStyle=isOut?"#00d4aa":"#6c63ff";c.globalAlpha=hl?1:.6;c.fill();',
      '    }else{c.beginPath();c.moveTo(sx,sy);c.lineTo(ex,ey);c.strokeStyle=dim?"rgba(255,255,255,.03)":"rgba(255,255,255,.1)";c.lineWidth=.9/z;c.globalAlpha=1;c.stroke();}',
      '    c.globalAlpha=1;',
      '  }',
      '  for(var vi=0;vi<vis.length;vi++){',
      '    var nv=vis[vi];var isSel=nv.id===sel;var isHov=nv.id===hov&&!isSel;var dimN=sel&&!isSel&&!sc[nv.id];',
      '    var r=nR(nv);var col=nCol(nv,cMode?"cluster":"ext");c.globalAlpha=dimN?.12:1;',
      '    if(isSel){c.beginPath();c.arc(nv.x,nv.y,r+10,0,Math.PI*2);c.fillStyle="rgba(0,212,170,.08)";c.fill();c.beginPath();c.arc(nv.x,nv.y,r+5,0,Math.PI*2);c.fillStyle="rgba(0,212,170,.2)";c.fill();}',
      '    else if(isHov){c.beginPath();c.arc(nv.x,nv.y,r+7,0,Math.PI*2);c.fillStyle="rgba(255,255,255,.06)";c.fill();}',
      '    else if((nv._deg||0)>4){c.beginPath();c.arc(nv.x,nv.y,r+6,0,Math.PI*2);c.fillStyle=col+"18";c.fill();}',
      '    var gr=c.createRadialGradient(nv.x-r*.3,nv.y-r*.3,r*.05,nv.x,nv.y,r*1.1);',
      '    if(isSel){gr.addColorStop(0,"rgba(200,255,245,.97)");gr.addColorStop(.4,"rgba(0,212,170,.92)");gr.addColorStop(1,"rgba(0,80,60,.55)");}',
      '    else{var rc=parseInt(col.slice(1,3),16)||100;var gc=parseInt(col.slice(3,5),16)||100;var bc=parseInt(col.slice(5,7),16)||100;gr.addColorStop(0,"rgba("+(rc+90)+","+(gc+90)+","+(bc+90)+",.97)");gr.addColorStop(.4,"rgba("+rc+","+gc+","+bc+",.88)");gr.addColorStop(1,"rgba("+(rc>>1)+","+(gc>>1)+","+(bc>>1)+",.5)");}',
      '    c.beginPath();c.arc(nv.x,nv.y,r,0,Math.PI*2);c.fillStyle=gr;c.fill();',
      '    var sg=c.createRadialGradient(nv.x-r*.35,nv.y-r*.35,0,nv.x,nv.y,r);sg.addColorStop(0,"rgba(255,255,255,.5)");sg.addColorStop(.3,"rgba(255,255,255,.1)");sg.addColorStop(1,"rgba(255,255,255,0)");',
      '    c.beginPath();c.arc(nv.x,nv.y,r,0,Math.PI*2);c.fillStyle=sg;c.fill();',
      '    c.beginPath();c.ellipse(nv.x+r*.1,nv.y+r+2,r*.6,r*.16,0,0,Math.PI*2);c.fillStyle="rgba(0,0,0,.2)";c.fill();',
      '    if(z>.35||isSel||sc[nv.id]||hc[nv.id]){',
      '      var fs=Math.max(8,Math.min(11,10/z));c.font=(isSel?"700 ":((nv._deg||0)>3?"600 ":""))+fs+"px JetBrains Mono,monospace";c.textAlign="center";',
      '      c.fillStyle="rgba(13,15,20,.85)";c.fillText(nv.label,nv.x+.5,nv.y+r+fs+2.5);',
      '      c.fillStyle=isSel?"#00d4aa":(sc[nv.id]||hc[nv.id])?"#e2e4ed":((nv._deg||0)>3?col:"#9ca3af");c.fillText(nv.label,nv.x,nv.y+r+fs+2);',
      '    }',
      '    c.globalAlpha=1;',
      '  }',
      '  c.restore();',
      '}',
      '',
      'function drawMinimap(){',
      '  if(!showMinimap||!ready){return;}',
      '  var mW=mmCanvas.width=160,mH=mmCanvas.height=110;mmCtx.clearRect(0,0,mW,mH);',
      '  var minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;',
      '  for(var i=0;i<nodes.length;i++){var n=nodes[i];minX=Math.min(minX,n.x);maxX=Math.max(maxX,n.x);minY=Math.min(minY,n.y);maxY=Math.max(maxY,n.y);}',
      '  var bW=Math.max(maxX-minX,1),bH=Math.max(maxY-minY,1);',
      '  var scale=Math.min(mW/bW,mH/bH)*.85;var ox=(mW-bW*scale)/2,oy=(mH-bH*scale)/2;',
      '  mmCtx.strokeStyle="rgba(255,255,255,.08)";mmCtx.lineWidth=.5;',
      '  for(var ei=0;ei<edges.length;ei++){var e=edges[ei];var na=findN(e.from),nb=findN(e.to);if(!na||!nb){continue;}mmCtx.beginPath();mmCtx.moveTo(ox+(na.x-minX)*scale,oy+(na.y-minY)*scale);mmCtx.lineTo(ox+(nb.x-minX)*scale,oy+(nb.y-minY)*scale);mmCtx.stroke();}',
      '  for(var ni=0;ni<nodes.length;ni++){var nv=nodes[ni];var mx=ox+(nv.x-minX)*scale,my=oy+(nv.y-minY)*scale;var mr=Math.max(1.5,nR(nv)*scale*.3);mmCtx.beginPath();mmCtx.arc(mx,my,mr,0,Math.PI*2);mmCtx.fillStyle=nv.id===selId?"#00d4aa":(EC[nv.ext]||"#6c63ff");mmCtx.fill();}',
      '  var vpX=(-panX/zoom-minX)*scale+ox;var vpY=(-panY/zoom-minY)*scale+oy;',
      '  var vpW=(canvas.width/zoom)*scale;var vpH=(canvas.height/zoom)*scale;',
      '  mmViewport.style.left=Math.max(0,vpX)+"px";mmViewport.style.top=Math.max(0,vpY)+"px";',
      '  mmViewport.style.width=Math.min(vpW,mW)+"px";mmViewport.style.height=Math.min(vpH,mH)+"px";',
      '}',
      '',
      'function doZoom(factor,cx,cy){var newZ=Math.max(.05,Math.min(zoom*factor,12));panX=cx-(cx-panX)*newZ/zoom;panY=cy-(cy-panY)*newZ/zoom;zoom=newZ;updateZoomUI();}',
      'function zoomIn(){doZoom(1.3,canvas.width/2,canvas.height/2);}',
      'function zoomOut(){doZoom(.77,canvas.width/2,canvas.height/2);}',
      'function zoomFit(){',
      '  if(!nodes.length){return;}',
      '  var minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;',
      '  for(var i=0;i<nodes.length;i++){var n=nodes[i];minX=Math.min(minX,n.x-nR(n));maxX=Math.max(maxX,n.x+nR(n));minY=Math.min(minY,n.y-nR(n));maxY=Math.max(maxY,n.y+nR(n));}',
      '  var bW=maxX-minX,bH=maxY-minY;if(bW<1||bH<1){return;}',
      '  zoom=Math.max(.05,Math.min(Math.min(canvas.width/bW,canvas.height/bH)*.88,8));',
      '  panX=(canvas.width-bW*zoom)/2-minX*zoom;panY=(canvas.height-bH*zoom)/2-minY*zoom;updateZoomUI();',
      '}',
      'function zoomTo100(){zoom=1;panX=0;panY=0;updateZoomUI();}',
      'function updateZoomUI(){document.getElementById("zoom-val").textContent=Math.round(zoom*100)+"%";}',
      '',
      'function openFullscreen(){',
      '  fsActive=true;',
      '  fsPanX=panX;fsPanY=panY;fsZoom=zoom;',
      '  document.getElementById("fs-overlay").style.display="flex";',
      '  requestAnimationFrame(function(){',
      '    var tb=document.getElementById("fs-toolbar");',
      '    var tbH=tb?tb.offsetHeight:52;',
      '    var W=window.innerWidth;',
      '    var H=window.innerHeight-tbH;',
      '    fsCanvas.width=Math.max(W,100);',
      '    fsCanvas.height=Math.max(H,100);',
      '    fsCanvas.style.width=fsCanvas.width+"px";',
      '    fsCanvas.style.height=fsCanvas.height+"px";',
      '    fsCtx=fsCanvas.getContext("2d");',
      '  });',
      '}',
      '',
      'function closeFullscreen(){',
      '  fsActive=false;',
      '  panX=fsPanX;panY=fsPanY;zoom=fsZoom;',
      '  updateZoomUI();',
      '  document.getElementById("fs-overlay").style.display="none";',
      '}',
      '',
      'function fsFit(){',
      '  if(!nodes.length){return;}',
      '  var minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;',
      '  for(var i=0;i<nodes.length;i++){var n=nodes[i];minX=Math.min(minX,n.x);maxX=Math.max(maxX,n.x);minY=Math.min(minY,n.y);maxY=Math.max(maxY,n.y);}',
      '  var pw=fsCanvas.width,ph=fsCanvas.height,bW=maxX-minX,bH=maxY-minY;if(bW<1||bH<1){return;}',
      '  fsZoom=Math.max(.05,Math.min(Math.min(pw/bW,ph/bH)*.88,8));',
      '  fsPanX=(pw-bW*fsZoom)/2-minX*fsZoom;fsPanY=(ph-bH*fsZoom)/2-minY*fsZoom;',
      '}',
      'function fsDoZoom(f,cx,cy){var mx=cx!==undefined?cx:fsCanvas.width/2,my=cy!==undefined?cy:fsCanvas.height/2;var nz=Math.max(.05,Math.min(fsZoom*f,12));fsPanX=mx-(mx-fsPanX)*nz/fsZoom;fsPanY=my-(my-fsPanY)*nz/fsZoom;fsZoom=nz;}',
      '',
      'function exportPNG(){',
      '  var off=document.createElement("canvas");off.width=canvas.width;off.height=canvas.height;',
      '  var oc=off.getContext("2d");oc.fillStyle="#0d0f14";oc.fillRect(0,0,off.width,off.height);',
      '  drawGraph(oc,panX,panY,zoom,filterText,selId,hovId,clusterMode,clusterFocus);',
      '  var a=document.createElement("a");a.href=off.toDataURL("image/png");a.download="dependency-graph.png";document.body.appendChild(a);a.click();document.body.removeChild(a);',
      '}',
      '',
      'function showInfoPanel(n){',
      '  var panel=document.getElementById("info-panel");',
      '  var deps=[],used=[];',
      '  for(var i=0;i<edges.length;i++){if(edges[i].from===n.id){deps.push(edges[i].to);}if(edges[i].to===n.id){used.push(edges[i].from);}}',
      '  var col=EC[n.ext]||"#6c63ff";',
      '  var dH=deps.slice(0,12).map(function(d){var nd=findN(d);var l=nd?nd.label:d.split("/").pop();return"<span class=\'ip-badge\' onclick=\'jumpTo(\\""+d+"\\")\'>\u2192 "+l+"</span>";}).join("")+(deps.length>12?"<span style=\'color:var(--muted)\'>+more</span>":"");',
      '  var uH=used.slice(0,12).map(function(d){var nd=findN(d);var l=nd?nd.label:d.split("/").pop();return"<span class=\'ip-badge\' onclick=\'jumpTo(\\""+d+"\\")\'>\u2190 "+l+"</span>";}).join("")+(used.length>12?"<span style=\'color:var(--muted)\'>+more</span>":"");',
      '  panel.innerHTML="<span class=\'ip-close\' onclick=\'closeInfoPanel()\'>&#x2715;</span><div class=\'ip-title\' style=\'color:"+col+"\'>"+n.id+"</div><div class=\'ip-stat\'><span class=\'ip-stat-label\'>Type</span><span class=\'ip-stat-val\'>"+(n.ext||"?").toUpperCase()+"</span></div><div class=\'ip-stat\'><span class=\'ip-stat-label\'>Folder</span><span class=\'ip-stat-val\' style=\'font-size:9px\'>"+n.folder+"</span></div><div class=\'ip-stat\'><span class=\'ip-stat-label\'>Connections</span><span class=\'ip-stat-val\'>"+(n._deg||0)+"</span></div><div class=\'ip-stat\'><span class=\'ip-stat-label\'>Imports</span><span class=\'ip-stat-val\'>"+deps.length+"</span></div><div class=\'ip-stat\'><span class=\'ip-stat-label\'>Used by</span><span class=\'ip-stat-val\'>"+used.length+"</span></div>"+(deps.length?"<div class=\'ip-section\'><div class=\'ip-label\'>Imports</div>"+dH+"</div>":"")+(used.length?"<div class=\'ip-section\'><div class=\'ip-label\'>Used by</div>"+uH+"</div>":"");',
      '  panel.style.display="block";',
      '}',
      'function closeInfoPanel(){document.getElementById("info-panel").style.display="none";}',
      'function jumpTo(id){var n=findN(id);if(!n){return;}selId=id;panX=canvas.width/2-n.x*zoom;panY=canvas.height/2-n.y*zoom;showInfoPanel(n);}',
      '',
      'function toggleCluster(){clusterMode=!clusterMode;clusterFocus=null;document.getElementById("cluster-btn").classList.toggle("active",clusterMode);buildClusterBar();}',
      'function buildClusterBar(){',
      '  var bar=document.getElementById("cluster-bar");if(!clusterMode){bar.innerHTML="";bar.style.display="none";return;}',
      '  var folders={};for(var i=0;i<nodes.length;i++){var f=nodes[i].folder;if(!folders[f]){folders[f]=0;}folders[f]++;}',
      '  var html="<span style=\'font-family:var(--mono);font-size:10px;color:var(--muted);margin-right:8px\'>Folders:</span><span class=\'cluster-badge\' style=\'background:rgba(255,255,255,.08);color:var(--text)\' onclick=\'setClusterFocus(null)\'>All</span>";',
      '  for(var f in folders){var col=FOLDER_COLORS[folderMap[f]||0];var isA=clusterFocus===f;html+="<span class=\'cluster-badge\' style=\'background:"+col+"20;border:1px solid "+col+"50;color:"+col+";outline:"+(isA?"2px solid "+col:"none")+"\' onclick=\'setClusterFocus(\\""+f+"\\")\'>"+(f.split("/").pop()||f)+" ("+folders[f]+")</span>";}',
      '  bar.innerHTML=html;bar.style.display="flex";',
      '}',
      'function setClusterFocus(f){clusterFocus=f;buildClusterBar();}',
      '',
      'function doSearch(q){filterText=q.toLowerCase();filterActive=q.length>0;document.getElementById("search-clear").style.display=q?"block":"none";if(q.length>1){var m=nodes.filter(function(n){return n.id.toLowerCase().indexOf(filterText)!==-1||n.label.toLowerCase().indexOf(filterText)!==-1;});if(m.length===1){jumpTo(m[0].id);}}}',
      'function clearSearch(){document.getElementById("graph-search").value="";doSearch("");}',
      '',
      'function showKbdHints(){document.getElementById("kbd-hints").style.display="block";}',
      'function hideKbdHints(){document.getElementById("kbd-hints").style.display="none";}',
      'document.addEventListener("keydown",function(e){',
      '  if(e.target.tagName==="INPUT"){return;}',
      '  if(e.key==="Escape"){if(fsActive){closeFullscreen();}else{hideKbdHints();closeInfoPanel();selId=null;}}',
      '  if(e.key==="f"||e.key==="F"){if(!e.ctrlKey&&!e.metaKey){if(fsActive){closeFullscreen();}else{openFullscreen();}}}',
      '  if(!fsActive){',
      '    if(e.key==="+"||e.key==="="){zoomIn();}if(e.key==="-"){zoomOut();}if(e.key==="0"){zoomFit();}',
      '    if(e.key==="1"){zoomTo100();}if(e.key==="r"||e.key==="R"){if(!e.ctrlKey){resetView();}}',
      '    if(e.key==="c"||e.key==="C"){if(!e.ctrlKey){toggleCluster();}}',
      '    if(e.key==="m"||e.key==="M"){showMinimap=!showMinimap;document.getElementById("mm-wrap").style.display=showMinimap?"block":"none";}',
      '  }',
      '  if(e.key==="?"){showKbdHints();}',
      '});',
      '',
      'function nodeAt(mx,my,pX,pY,z){var wx=(mx-pX)/z,wy=(my-pY)/z;for(var i=nodes.length-1;i>=0;i--){var n=nodes[i],r=nR(n)+5;if((n.x-wx)*(n.x-wx)+(n.y-wy)*(n.y-wy)<r*r){return n;}}return null;}',
      '',
      'function showTip(t,n,cx,cy){',
      '  if(!n){t.style.display="none";return;}',
      '  var deps=[],used=[];for(var i=0;i<edges.length;i++){if(edges[i].from===n.id){deps.push(edges[i].to.split("/").pop());}if(edges[i].to===n.id){used.push(edges[i].from.split("/").pop());}}',
      '  var col=EC[n.ext]||"#6c63ff";',
      '  var dB=deps.slice(0,6).map(function(d){return"<span class=\'tt-badge\'>"+d+"</span>";}).join("");',
      '  var uB=used.slice(0,6).map(function(d){return"<span class=\'tt-badge\'>"+d+"</span>";}).join("");',
      '  t.innerHTML="<div class=\'tt-name\' style=\'color:"+col+"\'>"+n.id+"</div><div class=\'tt-row\'><span style=\'color:var(--muted)\'>Type: </span><span class=\'tt-hl\'>"+(n.ext||"?").toUpperCase()+"</span></div><div class=\'tt-row\'><span style=\'color:var(--muted)\'>Connections: </span><span class=\'tt-hl\'>"+(n._deg||0)+"</span></div>"+(deps.length?"<div style=\'margin-top:6px;color:var(--muted);font-size:9px\'>IMPORTS</div><div>"+dB+(deps.length>6?"\u2026":"")+"</div>":"")+(used.length?"<div style=\'margin-top:6px;color:var(--muted);font-size:9px\'>USED BY</div><div>"+uB+(used.length>6?"\u2026":"")+"</div>":"");',
      '  t.style.display="block";t.style.left=(cx+16)+"px";t.style.top=(cy-12)+"px";',
      '}',
      '',
      'canvas.addEventListener("mousedown",function(e){var n=nodeAt(e.offsetX,e.offsetY,panX,panY,zoom);if(n){dragN=n;n.fixed=true;selId=n.id;showInfoPanel(n);}else{selId=null;closeInfoPanel();isPan=true;panStart={x:e.offsetX-panX,y:e.offsetY-panY};}});',
      'canvas.addEventListener("mousemove",function(e){if(dragN){dragN.x=(e.offsetX-panX)/zoom;dragN.y=(e.offsetY-panY)/zoom;}else if(isPan){panX=e.offsetX-panStart.x;panY=e.offsetY-panStart.y;}var n=nodeAt(e.offsetX,e.offsetY,panX,panY,zoom);hovId=n?n.id:null;showTip(tip,n,e.clientX,e.clientY);canvas.style.cursor=n?"pointer":(isPan?"grabbing":"grab");});',
      'canvas.addEventListener("mouseup",function(){if(dragN){dragN.fixed=false;dragN=null;}isPan=false;});',
      'canvas.addEventListener("dblclick",function(e){var n=nodeAt(e.offsetX,e.offsetY,panX,panY,zoom);if(n){n.fixed=!n.fixed;}else{zoomFit();}});',
      'canvas.addEventListener("wheel",function(e){e.preventDefault();doZoom(e.deltaY>0?.88:1.12,e.offsetX,e.offsetY);},{passive:false});',
      '',
      'fsCanvas.addEventListener("mousedown",function(e){var n=nodeAt(e.offsetX,e.offsetY,fsPanX,fsPanY,fsZoom);if(n){fsDragN=n;n.fixed=true;selId=n.id;showInfoPanel(n);}else{selId=null;closeInfoPanel();fsIsPan=true;fsPanStart={x:e.offsetX-fsPanX,y:e.offsetY-fsPanY};}});',
      'fsCanvas.addEventListener("mousemove",function(e){if(fsDragN){fsDragN.x=(e.offsetX-fsPanX)/fsZoom;fsDragN.y=(e.offsetY-fsPanY)/fsZoom;}else if(fsIsPan){fsPanX=e.offsetX-fsPanStart.x;fsPanY=e.offsetY-fsPanStart.y;}var n=nodeAt(e.offsetX,e.offsetY,fsPanX,fsPanY,fsZoom);hovId=n?n.id:null;showTip(fsTip,n,e.clientX,e.clientY);fsCanvas.style.cursor=n?"pointer":(fsIsPan?"grabbing":"grab");});',
      'fsCanvas.addEventListener("mouseup",function(){if(fsDragN){fsDragN.fixed=false;fsDragN=null;}fsIsPan=false;});',
      'fsCanvas.addEventListener("dblclick",function(e){var n=nodeAt(e.offsetX,e.offsetY,fsPanX,fsPanY,fsZoom);if(n){n.fixed=!n.fixed;}else{fsFit();}});',
      'fsCanvas.addEventListener("wheel",function(e){e.preventDefault();fsDoZoom(e.deltaY>0?.88:1.12,e.offsetX,e.offsetY);},{passive:false});',
      '',
      'mmCanvas.addEventListener("click",function(e){',
      '  if(!ready||!nodes.length){return;}',
      '  var minX=Infinity,maxX=-Infinity,minY=Infinity,maxY=-Infinity;',
      '  for(var i=0;i<nodes.length;i++){var n=nodes[i];minX=Math.min(minX,n.x);maxX=Math.max(maxX,n.x);minY=Math.min(minY,n.y);maxY=Math.max(maxY,n.y);}',
      '  var bW=Math.max(maxX-minX,1),bH=Math.max(maxY-minY,1);var mW=mmCanvas.width,mH=mmCanvas.height;',
      '  var scale=Math.min(mW/bW,mH/bH)*.85;var ox=(mW-bW*scale)/2,oy=(mH-bH*scale)/2;',
      '  panX=canvas.width/2-((e.offsetX-ox)/scale+minX)*zoom;panY=canvas.height/2-((e.offsetY-oy)/scale+minY)*zoom;',
      '});',
      '',
      'new ResizeObserver(function(){doResize();}).observe(document.getElementById("canvas-wrap"));',
      'new ResizeObserver(function(){',
      '  if(fsActive){',
      '    var W=window.innerWidth;var tb=document.getElementById("fs-toolbar");',
      '    var H=window.innerHeight-(tb?tb.offsetHeight:52);',
      '    if(W>10&&H>10){fsCanvas.width=W;fsCanvas.height=H;fsCanvas.style.width=W+"px";fsCanvas.style.height=H+"px";fsCtx=fsCanvas.getContext("2d");}',
      '  }',
      '}).observe(document.getElementById("fs-canvas-wrap"));',
      '',
      'function loop(){',
      '  simulate(canvas.width,canvas.height);',
      '  drawGraph(ctx,panX,panY,zoom,filterText,selId,hovId,clusterMode,clusterFocus);',
      '  if(showMinimap&&simTick%3===0){drawMinimap();}',
      '  var vis=0,ec=0,vset={};',
      '  for(var ni=0;ni<nodes.length;ni++){var n=nodes[ni];var fM=!filterText||n.id.toLowerCase().indexOf(filterText)!==-1;var cM=!clusterMode||!clusterFocus||n.folder===clusterFocus;if(fM&&cM){vset[n.id]=true;vis++;}}',
      '  for(var ei=0;ei<edges.length;ei++){if(vset[edges[ei].from]&&vset[edges[ei].to]){ec++;}}',
      '  statsEl.textContent=vis+" files \u00b7 "+ec+" imports";',
      '  if(fsActive&&fsCtx&&fsCanvas.width>10){',
      '    drawGraph(fsCtx,fsPanX,fsPanY,fsZoom,filterText,selId,hovId,clusterMode,clusterFocus);',
      '  }',
      '  requestAnimationFrame(loop);',
      '}',
      '',
      'doResize();',
      'updateZoomUI();',
      'loop();',
    ].join('\n');

    const html = [
      '<!DOCTYPE html><html><head><meta charset="UTF-8"><style>' + css + '</style></head>',
      '<body><div id="app">',
      '<div id="toolbar">',
      '  <span id="toolbar-title">&#x1F4C1; Dependency Graph</span>',
      '  <div class="tb-sep"></div>',
      '  <div class="zoom-group">',
      '    <button class="tb-btn" onclick="zoomOut()">&#x2212;</button>',
      '    <span id="zoom-val">100%</span>',
      '    <button class="tb-btn" onclick="zoomIn()">+</button>',
      '  </div>',
      '  <button class="tb-btn" onclick="zoomFit()">&#x25A1; Fit</button>',
      '  <button class="tb-btn" onclick="zoomTo100()">1:1</button>',
      '  <div class="tb-sep"></div>',
      '  <button class="tb-btn" onclick="resetView()">&#x1F504; Reset</button>',
      '  <div class="tb-sep"></div>',
      '  <div id="search-wrap">',
      '    <input id="graph-search" placeholder="&#x1F50D; Search files\u2026" oninput="doSearch(this.value)">',
      '    <span id="search-clear" onclick="clearSearch()">&#x2715;</span>',
      '  </div>',
      '  <div class="tb-sep"></div>',
      '  <button class="tb-btn" id="cluster-btn" onclick="toggleCluster()">&#x1F5C2; Cluster</button>',
      '  <button class="tb-btn" onclick="document.getElementById(\'mm-wrap\').style.display=document.getElementById(\'mm-wrap\').style.display===\'none\'?\'block\':\'none\'">&#x1F5FA; Map</button>',
      '  <button class="tb-btn" onclick="exportPNG()">&#x1F4F7; Export</button>',
      '  <span class="spacer"></span>',
      '  <span id="graph-stats"></span>',
      '  <button class="tb-btn" onclick="showKbdHints()">&#x2328; Keys</button>',
      '  <button class="tb-btn" onclick="openFullscreen()" style="border-color:var(--accent);color:var(--accent)">&#x26F6; Fullscreen</button>',
      '</div>',
      '<div id="cluster-bar" style="display:none;align-items:center;flex-wrap:wrap;gap:6px;padding:6px 14px;background:var(--surface2);border-bottom:1px solid var(--border);flex-shrink:0"></div>',
      '<div id="canvas-wrap">',
      '  <canvas id="graph-canvas"></canvas>',
      '  <div id="tooltip"></div>',
      '  <div id="info-panel"></div>',
      '  <div id="mm-wrap" style="position:absolute;bottom:10px;right:10px;z-index:10">',
      '    <canvas id="mm-canvas" width="160" height="110" style="display:block;border-radius:8px;border:1px solid var(--border)"></canvas>',
      '    <div id="minimap-viewport" style="position:absolute;border:1.5px solid var(--accent2);border-radius:2px;pointer-events:none;opacity:.7;top:0;left:0;width:40px;height:30px"></div>',
      '    <span style="position:absolute;bottom:4px;left:7px;font-size:9px;color:var(--muted);font-family:var(--mono);pointer-events:none">minimap</span>',
      '  </div>',
      '  <div id="kbd-hints">',
      '    <span class="kh-close" onclick="hideKbdHints()">&#x2715;</span>',
      '    <h3>&#x2328; Keyboard Shortcuts</h3>',
      '    <div class="krow"><kbd>+</kbd><kbd>=</kbd><span>Zoom in</span></div>',
      '    <div class="krow"><kbd>-</kbd><span>Zoom out</span></div>',
      '    <div class="krow"><kbd>0</kbd><span>Fit all nodes</span></div>',
      '    <div class="krow"><kbd>1</kbd><span>Reset to 100%</span></div>',
      '    <div class="krow"><kbd>F</kbd><span>Toggle fullscreen</span></div>',
      '    <div class="krow"><kbd>R</kbd><span>Reset layout</span></div>',
      '    <div class="krow"><kbd>C</kbd><span>Cluster by folder</span></div>',
      '    <div class="krow"><kbd>M</kbd><span>Toggle minimap</span></div>',
      '    <div class="krow"><kbd>Esc</kbd><span>Close / deselect</span></div>',
      '    <div class="krow"><kbd>Dblclick</kbd><span>Pin node / Fit (empty)</span></div>',
      '    <div class="krow"><kbd>Scroll</kbd><span>Zoom at cursor</span></div>',
      '    <div class="krow"><kbd>Drag</kbd><span>Pan / Move node</span></div>',
      '  </div>',
      '</div>',
      '<div id="legend">',
      '  <div class="leg"><div class="dot" style="background:#5ba3f5"></div>.ts/.tsx</div>',
      '  <div class="leg"><div class="dot" style="background:#f0c030"></div>.js/.jsx</div>',
      '  <div class="leg"><div class="dot" style="background:#4caf50"></div>.py</div>',
      '  <div class="leg"><div class="dot" style="background:#ab77f7"></div>.css/.scss</div>',
      '  <div class="leg"><div class="dot" style="background:#f07070"></div>.html</div>',
      '  <div class="leg"><div class="dot" style="background:#4db6ac"></div>.json</div>',
      '  <div class="leg"><div class="dot" style="background:#3a3f50"></div>standalone</div>',
      '  <span class="hint">Click=select · Drag=move · Dblclick=pin · ?=shortcuts</span>',
      '</div>',
      '<div id="fs-overlay">',
      '  <div id="fs-toolbar">',
      '    <span style="font-size:13px;font-weight:800;color:var(--text)">&#x1F4C1; Dependency Graph — Fullscreen</span>',
      '    <div class="tb-sep"></div>',
      '    <div class="zoom-group">',
      '      <button class="tb-btn" onclick="fsDoZoom(.77)">&#x2212;</button>',
      '      <button class="tb-btn" onclick="fsDoZoom(1.3)">+</button>',
      '    </div>',
      '    <button class="tb-btn" onclick="fsFit()">&#x25A1; Fit</button>',
      '    <div class="tb-sep"></div>',
      '    <input id="fs-search" style="background:var(--surface2);border:1px solid var(--border);color:var(--text);padding:5px 10px;border-radius:6px;font-size:11px;width:180px;outline:none;font-family:var(--mono)" placeholder="&#x1F50D; Search\u2026" oninput="doSearch(this.value);document.getElementById(\'graph-search\').value=this.value">',
      '    <span class="spacer"></span>',
      '    <button class="tb-btn" onclick="exportPNG()">&#x1F4F7; Export</button>',
      '    <button class="tb-btn" onclick="closeFullscreen()" style="border-color:var(--accent3);color:var(--accent3)">&#x2715; Exit</button>',
      '  </div>',
      '  <div id="fs-canvas-wrap">',
      '    <canvas id="fs-canvas"></canvas>',
      '    <div id="fs-tooltip"></div>',
      '  </div>',
      '</div>',
      '<script>' + js + '<\/script>',
      '</body></html>',
    ].join('\n');

    return html;
  }
}
